create database customer_behavior;
select * from customer limit 20;

-- Q1 What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2 Which customers used a discount but  still more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount)  from customer);

-- Q3 Which are the top 5 products with the highest average review rating?
select item_purchased as products, ROUND(AVG(CAST(review_rating AS DECIMAL)), 2) AS avg_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4 Compare the average purchase amounts between standard and express shipping.
select round(avg(purchase_amount),2) as average_purchase, shipping_type
from customer
where shipping_type in('Express','Standard')
group by shipping_type;

-- Q5 Do subscribed customers spend more? compare average spend and total revenue between 
-- subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(sum(purchase_amount),2) as revenue,
round(avg(purchase_amount),2) as avg_spend
from customer
group by subscription_status;

-- Q6 which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased AS product,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_perc
FROM customer
GROUP BY item_purchased
ORDER BY discount_perc DESC
LIMIT 5;